# Generated by Django 5.0.1 on 2024-01-22 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('beach', 'beach'), ('city', 'city'), ('remote', 'remote')], max_length=100, null=True)),
                ('accomodation', models.CharField(choices=[('motel', 'motel'), ('airbnb', 'airbnb'), ('hotel', 'hotel')], max_length=100, null=True)),
                ('guests', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('leisure', models.CharField(max_length=100, null=True)),
                ('checkin', models.DateField(null=True)),
                ('checkout', models.DateField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.project')),
            ],
        ),
    ]
