# Generated by Django 5.0.1 on 2024-01-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_project_title_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='accomodation',
            field=models.CharField(choices=[('airbnb', 'airbnb'), ('hotel', 'hotel'), ('motel', 'motel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='location',
            field=models.CharField(choices=[('remote', 'remote'), ('city', 'city'), ('beach', 'beach')], max_length=100, null=True),
        ),
    ]
