# Generated by Django 5.0.1 on 2024-01-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_accomodation_alter_survey_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='location',
            field=models.CharField(choices=[('remote', 'remote'), ('beach', 'beach'), ('city', 'city')], max_length=100, null=True),
        ),
    ]
