# Generated by Django 5.0.1 on 2024-01-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_survey_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='accomodation',
            field=models.CharField(choices=[('motel', 'motel'), ('airbnb', 'airbnb'), ('hotel', 'hotel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='location',
            field=models.CharField(choices=[('city', 'city'), ('remote', 'remote'), ('beach', 'beach')], max_length=100, null=True),
        ),
    ]
