# Generated by Django 5.0.1 on 2024-01-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_survey_name_alter_survey_accomodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='accomodation',
            field=models.CharField(choices=[('airbnb', 'airbnb'), ('hotel', 'hotel'), ('motel', 'motel')], max_length=100, null=True),
        ),
    ]
